# based on AutoCV by jitinnair1 and push ot other repo action by dmnemec
name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Edit here with the names of your latex file and directory (can use ".")
      DIR: .
      FILE: felknerresume
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: cv
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE }}
          working_directory: ${{ env.DIR }}
      - name: move
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts
  # now deploy to personal website
  copy-file:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: github_artifacts
      - name: push to website
        uses: dmnemec/copy_file_to_another_repo_action@main
        env: 
          API_TOKEN_GITHUB: ${{ secrets.GH_PAT }}
        with:
          source_file: 'github_artifacts/felknerresume.pdf'
          destination_repo: 'katyfelkner/website'
          destination_folder: ''
          destination_branch: 'master'
          user_email: 'felkner@usc.edu'
          user_name: 'katyfelkner'
          commit_message: 'auto-updated resume'
